client := "./Odyssey/Odyssey.csproj"
silo := "./Odyssey.Silo/Odyssey.Silo.csproj"
db_sys_cs := "postgres://postgres:postgres@192.168.1.213:5432/postgres"
db_cs := "postgres://postgres:postgres@192.168.1.213:5432/odyssey"

install:
    dcdn install

[arg('target', pattern='client|silo')]
build target:
    dotnet build {{ if target == "client" { client }  else  { silo } }}


[arg('target', pattern='client|silo')]
[arg('reload', short='r', long="hot-reload", value='')]
watch target reload='--no-hot-reload':
    DOTNET_WATCH_SUPPRESS_EMOJIS=1 dotnet watch --non-interactive --project {{ if target == "client" { "./Odyssey/Odyssey.csproj" } else { "./Odyssey.Silo/Odyssey.Silo.csproj" } }} {{ reload }}

add-migration name:
    PersistenceSettings__DatabaseSettings__Driver=Postgres \
    dotnet ef migrations add {{name}} \
        --project ./Odyssey.Persistence/Odyssey.Persistence.csproj \
        --context PostgresApplicationDbContext \
        --startup-project ./Odyssey.Silo/Odyssey.Silo.csproj \
        --output-dir ./Migrations/Postgres

db-init:
    psql "{{db_sys_cs}}" -c "CREATE DATABASE odyssey;"

db-drop:
    psql "{{db_sys_cs}}" -c "DROP DATABASE odyssey;"

db-reset:
    psql "{{db_sys_cs}}" -c "DROP DATABASE IF EXISTS odyssey;"
    psql "{{db_sys_cs}}" -c "CREATE DATABASE odyssey;"

db:
    lazysql "{{db_cs}}?sslmode=disable"

pm:
    podman system service --time=0
